### ISSUE TITLE
Tempban required a way to determine the duration, and allow the bot to continue the background count.

### ISSUE THREAD

**Issue by jstan425** [jstan425/Cookie-Bot#3]
After initiating the tempban which is ban a user for x duration, and unban them when the duration ends. Technically, if the bot runs 24/7. It is fine to use asyncio sleep(time). But if the bot went offline, we need to find a way to get the bot to generate the data that the datetime that is tempban. So, that when the bot is online again. It will crosscheck the database whether in flat file, or mysql for the differences which match the criteria of x duration.

**Comment by jstan425** [comment]
The tempban is now able to differentiate the timing, however is unable to process the cmd. looking into solution on this matter.

**Comment by ate-it** [comment]
> The tempban is now able to differentiate the timing, however is unable to process the cmd. looking into solution on this matter.

I'm happy to pick this up, using tasks is likely the solution, I haven't had a chance to play as of yet :) @jstan425
